project:
  type: book
  output-dir: docs

book:
  title: "Analyse de Données"
  author: "Benoît Simon-Bouhet"
  date: now
  date-format: "D MMMM YYYY"
  search: true
  repo-url: "https://github.com/besibo/DataAnalysis"
  chapters:
    - index.qmd
    - 01-RBasics.qmd
    - 02-Dataset.qmd
    - 03-Visualization.qmd
    - 04-TidyData.qmd
    - 05-DataWrangling.qmd
    - 06-EDA.qmd
    - 07-Incertitude.qmd
    - 08-ErrorBars.qmd
    - 09-OneSampleTests.qmd
    - 10-TwoSamplePairedTests.qmd
    - 11-TwoSampleTests.qmd
    - 12-ANOVA.qmd
    - 13-Correlation.qmd
    - 14-Regression.qmd
    - 15-PropTests.qmd
    - 16-GoodnessFit.qmd
    - references.qmd
  
crossref:
  chapters: true

bibliography: all.bib
lang: fr
title-block-banner: true
reference-location: margin
number-sections: true

language:
  title-block-author-single: "Auteur"
  title-block-published: "Dernière Mise à jour"

format:
  html:
    theme: 
      light: MyUnited.scss
      dark: MyUnited-dark.scss
    include-in-header: mathjax-config.html
    html-math-method:
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml-nofont.js"
    highlight-style: atom-one
    toc: true
    toc-depth: 3
    toc-location: right
    number-depth: 3
    # code-tools:
    #   source: false
    #   toggle: true
    # code-fold: show
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-depth: 5
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
